### ISSUE TITLE
Shaders and RAM usage

### ISSUE THREAD

**Issue by hlolli** [overtone/shadertone#30]
Hello, this is not a issue or a bug, but a thought about possible enhancement. I've noticed when reloading shaders the process "Java" can reach up to 7-8gb of RAM usage, thus slowing everything down. I can post an extract from the code I'm using, but in general, I think this is caused by not deleting zombies and/or past information. But could be caused by other factors in my code. I usually use midi for VJ-ing.

```clojure
  (def SHADER1 "
  uniform float iGlobalTime;
uniform vec3 iResolution;
uniform vec3 i13;
uniform float i4;
uniform vec3 i57;
uniform float i8;
uniform float iOvertoneVolume;
uniform sampler2D iChannel0;
//  #define time  iGlobalTime
//  #define R iResolution.xy
void main(void)
{

   //vec2 pos = (gl_FragCoord.xy/iResolution.xy) * 8. - 4.;
   vec2 pos = (gl_FragCoord.xy/iResolution.xy) * (10.*i4) - (5.*i57.x);
    pos.x *= iResolution.x / iResolution.y;
    float s = (.25*i57.y), f = .0, k = f;
    vec3 p = vec3(pos, sin(iOvertoneVolume* iGlobalTime * i13.x) * i13.y - i13.z)* s;

    for( int i=0; i< 10; i++ )
    {
           p = abs(p)/dot(p,p)- (1.65*i57.z);
           k = length(p) ;
           p = p*k+k;
   }

   f = dot(p,p)* s;
   gl_FragColor= vec4(f*.5, f *(1.2*i8), f * (5.*i8), 1.);;
}
")

(def shaderut (atom SHADER1))

(def MPKmini (midi-find-connected-device "MPK mini"))
(def i13 (atom [0.5 0.5 0.5]))
(def i4   (atom [0.15]))
(def i57 (atom [0.5 0.5 0.5]))
(def i8   (atom [0.5]))

(on-event (conj (midi-mk-full-device-key MPKmini) :control-change)
          (fn [m] (let [test (:data1 m)]
                   (case test
                     1 (swap! i13  assoc 0 (/ (:data2 m) 127))
                     2 (swap! i13  assoc 1 (/ (:data2 m) 127))
                     3 (swap! i13  assoc 2 (/ (:data2 m) 127))
                     4 (swap! i4   assoc 0 (/ (:data2 m) 127))
                     5 (swap! i57  assoc 0 (/ (:data2 m) 127))
                     6 (swap! i57  assoc 1 (/ (:data2 m) 127))
                     7 (swap! i57  assoc 2 (/ (:data2 m) 127))
                     8 (swap! i8   assoc 0 (/ (:data2 m) 127))
                     nil)))
          ::MPK-knobs)

(on-event [:midi :note-on]
           (fn [m] (let [test (:note m)]
                    (case test
                      48 (reset! shaderut SHADER1)
                      49 (reset! shaderut  SHADER2)
                      50 (reset! shaderut  SHADER3)
                      51 (reset! shaderut  SHADER4)
                      52 (reset! shaderut  SHADER6)
                      nil)))
           ::MPK-keys))

(defmacro glsl_boot [] (t/start shaderut
                                :width 800
                                :height 600
                                :textures [:overtone-audio]
                                :user-data {
                                                 "i13" i13
                                                 "i4" i4
                                                 "i57" i57
                                                 "i8" i8
                                                 }))
;Start the Shaders
(comment (glsl_boot))
```

**Comment by rogerallen** [comment]
Okay, I'll take a look.  I believe you're saying if you get midi note-on of 48-52, you change the shader, which causes a compile/reload of that shader and the old resources are not disposed, adding up over time.  Let me know if your understanding differs.

I should be able to make a testcase and try to repro.  I do have to say that memory issues in Clojure are not my strong suit...we'll see if I can figure this out.

**Comment by rogerallen** [comment]
Just FYI.  I'm unable to repro with this simple test.  Used memory actually decreases as the JVM apparently learns & the JIT does its thing.  I ran the `dotimes` function several times to try to see what happens.

```
(ns shadertone.footst
  (:require [shadertone.shader :as s]))

(def shader1 "
uniform float iGlobalTime;
uniform vec4 iColor;
void main(void) {
  gl_FragColor = iColor * abs(sin(iGlobalTime));
}")

(def shader2 "
uniform float iGlobalTime;
uniform vec4 iColor;
void main(void) {
  gl_FragColor = iColor * abs(sin(iGlobalTime*20.0));
}")

(def color (atom [1.0 0.5 0.0 1.0]))
(def shader (atom shader1))

(comment

  (s/start shader :user-data { "iColor" color})

  (dotimes [i 60]
    (println i "shader2")
    (reset! shader shader2)
    (Thread/sleep 200)
    (println i "shader1")
    (reset! shader shader1)
    (swap! color (fn [x] [(- 1.0 (nth x 0)) (nth x 1) (- 1.0 (nth x 2)) (nth x 3)]))
    (Thread/sleep 200))

  (s/stop)

  )
```

**Comment by hlolli** [comment]
Ok, interesting, yes you did understand me correctly. Maybe it's the knobs that cause this, since assoc! on a atom adds value to vector? But still it makes no sense that it can add a 7gb ram. Let me try this tomorrow your dotimes test, and see if I can be more precise and more accurate with what causes my memory to fill up. Thanks of course!

**Comment by rogerallen** [comment]
Anything you can do to help Show me how to reproduce would be great. Note that my test didn't use overtone at all. 

I used jvisualvm to watch the memory usage.

**Comment by hlolli** [comment]
I did a screencast of the memory filling up, I noticed that changing shaders was not a factor. Maybe this is the shader code itself. But I'm still investigating this, let me see if I can reproduce this on another machine etc...

[![video of memory filling up](http://img.youtube.com/vi/Th-aHIiH7zQ/0.jpg)](http://www.youtube.com/watch?v=Th-aHIiH7zQ")

**Comment by rogerallen** [comment]
I need more information to proceed on this bug, if there is no update, I'll be closing this.

**Comment by hlolli** [comment]
Yes please close it for now. I can't reproduce it anyway anymore. Sorry for disappearing with this bug, but using the midi controller with shader did this strange thing, pile up the ram. Let's just close it for now.
