### ISSUE TITLE
Export result as an image sequence and a wav file

### ISSUE THREAD

**Issue by NightMachinery** [overtone/shadertone#32]

**Comment by rogerallen** [comment]
I think I'd suggest using screen-capture software for this.  E.g. https://obsproject.com/
Given a video-recording of the performance, you could export that as image sequences & audio file.

**Comment by NightMachinery** [comment]
That's the last resort.

**Comment by rogerallen** [comment]
Then I think we'll just have to agree to disagree on this.  I see using free screen/audio-capture as an easy fix.  If you have a pull request or something more solid to propose, you can reopen, but I really don't have the gumption to work on this given the solution exists.
